### ISSUE TITLE
Upload latest version to Rubygems

### ISSUE THREAD

**Issue by joao-esteves** [rjocoleman/labelary#2]
The latest commit updated the dependencies but didn't change the gem's version. In Rubygems, the older state of the repo is still what's available, a version from 2018.

Rubygems: https://rubygems.org/gems/labelary/versions/0.2.0

**Comment by PatrickFranken** [comment]
Would love to see this on Rubygems! Have to maintain a fork of this Gem just because of this...

**Comment by rjocoleman** [comment]
done! `ver 0.3.0`.

The only change is a version bump and the faraday dependency criteria.

https://github.com/rjocoleman/labelary/releases/tag/0.3.0
https://rubygems.org/gems/labelary/versions/0.3.0

**Comment by jbbonin** [comment]
@rjocoleman Can you do the same for the version 0.4.0 ? 🙏

**Comment by rjocoleman** [comment]
Thanks for the prod @jbbonin - I'll set up GH actions to publish the latest tag when pushed as I keep missing that!

**Comment by rjocoleman** [comment]
`v0.4.0` is now published to rubygems - sorry for the oversight!
