### ISSUE TITLE
render method is broken if called at the level class on ruby3 without naming arguments

### ISSUE THREAD

**Issue by aovertus** [rjocoleman/labelary#3]
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

https://github.com/rjocoleman/labelary/blob/master/lib/labelary/label.rb#L3-L5

Should be `**args`

Will open a PR if this can help anyone

**Comment by rjocoleman** [comment]
hey @aovertus nice catch. I see a reasonable amount of activity on this gem.

Is this change backwards compatible with 2.x? I'd be very happy to merge a PR and cut a release if we're not going to break anyone's deployment.

**Comment by aovertus** [comment]
Hi @rjocoleman sorry for the late response, I was looking at the Pull request notification and never looked at the issue ... 🙈 .

Yes the change is backward compatible as ruby `2.x` already handle `**args`, it enforce the hash instead of passing an array

**Comment by rjocoleman** [comment]
thanks!
