### ISSUE TITLE
Default label render only returns first page

### ISSUE THREAD

**Issue by pauloralves** [rjocoleman/labelary#7]
If not defined, gem's index value is set to `0`, returning only the first page on multiple labels documents as default.
I believe it makes more sense if the gem index value defaults to `''`, which will return all pages if the user doesn't specify the page they want.

http://labelary.com/service.html
![image](https://user-images.githubusercontent.com/13332400/222513673-f07bbcef-9f7b-44ac-aa2b-24233e19c037.png)

I'll open a PR with the proposed change for review.

**Comment by rjocoleman** [comment]
closed in #8

**Comment by rjocoleman** [comment]
Released in v0.5.0 here and on Rubygems. This is a breaking change for some users and details are in the release notes.

https://github.com/rjocoleman/labelary/releases/tag/v0.5.0
